#mysql-deployment.yaml
{{- define "my.mysql.data" -}}

name: {{ .Release.Name}}-mysql
labels:
  app: {{ .Release.Name }}-wp
selector: {{ .Values.selector | toYaml | nindent 2 }}
  app: {{ .Release.Name }}-wp
  tier: mysql
strategy:
  type: Recreate
containers:
- image: {{ .Values.images.mysql }}:{{ .Values.images.mtag }}
  name: mysql
  env_literal:
  - name: MYSQL_ROOT_PASSWORD
  venv_values_secret:
    - secret: {{ .Release.Name }}-secrets
      values:
        key: password
  env_values_configmap:
    - configmap: {{ .Release.Name }}-config
      values:
        var1: "MYSQL_USER"
        var2: "MYSQL_DATABASE"
  ports:
  - containerPort: {{ .Values.ports.containerPort_mysql }}
    name: mysql

{{- end -}}

{{ include "ph.deployment.render" (include "my.mysql.data" . | fromYaml ) }}
