{{ define "mysecret.secret.data"  }}
name: {{ .Release.Name }}-secrets
data:
  password: {{ .Values.secret.password}}

{{- end }}
{{ include "ph.secret.render" (include "mysecret.secret.data" . | fromYaml )  }}
