# secret.yaml

{{ define "mysecret.secret.data"  }}
name: {{ .Release.Name }}-secrets
type: Opaque
data: # aquí van os datos
  password: YWJjMTIzLg==

{{- end }}
{{ include "ph.secret.render" (include "mysecret.secret.data" . | fromYaml )  }}
