images:
  frontend:
    image: mysql


selector:
  app: mysql
  concern: testing
  project: wordpress-mysql

#values.yaml

data:
  name: "wordpress"

spec:
  tier: frontend
  strategy:
    type: Recreate
labels:
  tier: frontend

  
  
ports:
  containerport_wordpress: 80
  containerPort_mysql: 3306
  protocol: TCP
  port_service_wordpress: 8080
  targetport_service_wordpress: 80


frontend_ports:
  - service: 8080
    pod: 80
  ## Namespace
namespace: p-sanchez


  ## Disabling MariaDB
mariadb:
  enabled: false



  ## Env wordpress
env_wordpress:
  name: WORDPRESS_DB_HOST
  value: wordpress-mysql
  wordpressdbhost: mysql


  ## Env Mysql
mysql:
  name: mysqlRootPassword
  user: pablo
  database: wordpress

  ## Images
images:
  wordpress: wordpress
  wtag: 4.8-apache
  mysql: mysql
  mtag: 5.6
  
  ## Selector
selector:
  app: wordpress
  tier: frontend


ingress-nginx:
  controller:
    scope:
      enabled: true # defaults to .Release.Namespace
